# Generated by Django 5.1.2 on 2024-10-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_customhomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhomepage',
            name='service_description',
            field=models.TextField(blank=True, help_text='Description of the service.', null=True),
        ),
        migrations.AddField(
            model_name='customhomepage',
            name='service_icon_url',
            field=models.URLField(blank=True, help_text='Icon URL for the service.', null=True),
        ),
        migrations.AddField(
            model_name='customhomepage',
            name='service_title',
            field=models.CharField(blank=True, help_text='Title of the service.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customhomepage',
            name='services',
            field=models.JSONField(blank=True, help_text='List of services provided by the organization.', null=True),
        ),
    ]
