# Generated by Django 5.1.2 on 2024-10-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_customhomepage_service_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customhomepage',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='customhomepage',
            name='service_icon_url',
        ),
        migrations.RemoveField(
            model_name='customhomepage',
            name='service_title',
        ),
        migrations.RemoveField(
            model_name='customhomepage',
            name='services',
        ),
        migrations.AddField(
            model_name='customhomepage',
            name='service_descriptions',
            field=models.TextField(blank=True, help_text='Descriptions of the services.', null=True),
        ),
        migrations.AddField(
            model_name='customhomepage',
            name='service_icon_urls',
            field=models.URLField(blank=True, help_text='Icon URLs for the services.', null=True),
        ),
        migrations.AddField(
            model_name='customhomepage',
            name='service_titles',
            field=models.CharField(blank=True, help_text='Titles of the services.', max_length=255, null=True),
        ),
    ]
