# Generated by Django 5.1.2 on 2024-10-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_aboutussnippet_patientjourneysnippet_pricingsnippet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the portfolio item.', max_length=255)),
                ('description', models.TextField(help_text='Description for the portfolio item.')),
                ('link', models.URLField(help_text='Link for the portfolio item.')),
                ('image_url', models.URLField(help_text='URL for the portfolio item image.')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
            },
        ),
    ]
