# Generated by Django 5.1.2 on 2024-10-18 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('website', '0007_portfoliosnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientjourneysnippet',
            name='background_image',
            field=models.ForeignKey(blank=True, help_text='Background image for the patient journey section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
