# Generated by Django 5.1.2 on 2024-10-18 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('website', '0008_patientjourneysnippet_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliosnippet',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='portfoliosnippet',
            name='link',
        ),
        migrations.AddField(
            model_name='portfoliosnippet',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Portfolio image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
